descriptionカラムを追加
quest-academia/gikyusai2020summer-red-server pull request #35
Opened 2020-08-24 11:08 UTC by marimonon

descriptionカラムを追加、Seedを追加いたしました。
どうぞ、よろしくお願い致します。🙇‍♀️✨

2020-08-24 15:30 UTC, yuki-tachi0219 requested changes
いろいろ気を聞かせてくださりありがとうございます。
3つのpngファイルは使わないので消しておいてください 🌀 
それ以外は問題なさそうですね。

2020-08-24 15:30 UTC, yuki-tachi0219 commented on app/controllers/api/v1/quests_controller.rb
> +      params.require(:quest).permit(:title, :award, :description)
たしかにこれ追加すべきですね。私も気づきませんでした。 助かりました。

2020-08-24 15:30 UTC, yuki-tachi0219 commented on db/seeds.rb
> +  description: "ぷよぷよお肉に猛烈アタック！")
寝ながら猛烈アタックできるのはすごい

2020-08-24 22:53 UTC, marimonon commented on app/controllers/api/v1/quests_controller.rb
> +      params.require(:quest).permit(:title, :award, :description)
ありがとうございます！✨🙇‍♀️

2020-08-24 22:57 UTC, marimonon commented on db/seeds.rb
> +  description: "ぷよぷよお肉に猛烈アタック！")
そんなのがあったらいいなと思って書きました！←😃

2020-08-24 23:01 UTC, marimonon commented
画像を削除いたしました！！
よろしくお願い致します！

2020-08-25 01:28 UTC, yuki-tachi0219 approved these changes
![20161128132421](https://user-images.githubusercontent.com/53440378/91112238-83a41f00-e6bd-11ea-9d12-d9de0e8287e4.gif)

2020-08-25 13:37 UTC, merged